CREATE TABLE IF NOT EXISTS "users" (
   [ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);
CREATE TABLE IF NOT EXISTS "splits" (
   [ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   [UserID] INTEGER NOT NULL REFERENCES [users]([ID]) ON DELETE CASCADE,
   [Name] TEXT NOT NULL,
   [Description] TEXT NOT NULL
); 
CREATE TABLE IF NOT EXISTS "exercises" (
   [ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   [SplitID] INTEGER REFERENCES [splits]([ID]) ON DELETE CASCADE,
   [Name] TEXT NOT NULL,
   [Description] TEXT NOT NULL,
   [ImageID] INTEGER DEFAULT 0 REFERENCES [images]([ID]) ON DELETE SET DEFAULT,
   [WeightFrom] FLOAT NOT NULL DEFAULT 0,
   [WeightTo] FLOAT NOT NULL DEFAULT 0,
   [RepsFrom] INTEGER NOT NULL DEFAULT 0,
   [RepsTo] INTEGER NOT NULL DEFAULT 0,
   [Sets] INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "workouts" (
   [ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   [UserID] INTEGER NOT NULL REFERENCES [users]([ID]) ON DELETE CASCADE,
   [SplitID] INTEGER NOT NULL REFERENCES [splits]([ID]) ON DELETE CASCADE,
   [StartedAt] TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   [CompletedAt] TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "workout_sets" (
   [SetNumber] INTEGER NOT NULL,
   [WorkoutID] INTEGER NOT NULL REFERENCES [workouts]([ID]) ON DELETE CASCADE,
   [ExerciseID] INTEGER NOT NULL REFERENCES [exercises]([ID]) ON DELETE CASCADE,
   [StartedAt] TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   [CompletedAt] TIMESTAMP,
   [SetRating] TEXT NOT NULL DEFAULT "current",
   [WeightFrom] FLOAT NOT NULL DEFAULT 0,
   [WeightTo] FLOAT NOT NULL DEFAULT 0,
   [RepsFrom] INTEGER NOT NULL DEFAULT 0,
   [RepsTo] INTEGER NOT NULL DEFAULT 0,
   PRIMARY KEY (SetNumber, WorkoutID, ExerciseID)
);
CREATE TABLE IF NOT EXISTS "images" (
   [ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   [Content] BLOB NOT NULL,
   [ContentType] TEXT NOT NULL 
);
CREATE TRIGGER on_exercise_delete AFTER DELETE ON exercises BEGIN
  DELETE FROM images WHERE ID = old.ImageID;
END;







